.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. ach_qt test_ach_qt
clean: FORCE
	$(MAKE) -C .. ach_qt_clean test_ach_qt_clean
check: FORCE
	$(MAKE) -C .. test_ach_qt_check
ach-qt ach-qt.exe: FORCE
	 $(MAKE) -C .. ach_qt
